import { IDiagnosticApplication } from '../../models/cyber-org-profile';

export const myDiagnosticmockData: IDiagnosticApplication[] = [
  {
    id: 'd-1',
    label: 'Network Security Audit',
    organization: {
      name: 'Teralink NGO',
      sub: '',
      avatar: 'https://i.pravatar.cc/64?img=15',
    },
    type: 'Audit',
    requestedOn: '2025-07-16',
    completedOn: null,
    justification: 'I want to help...',
    status: 'Pending',
    progress: '—',
  },
  {
    id: 'd-2',
    label: 'Network Security Audit',
    organization: {
      name: 'Teralink NGO',
      sub: '',
      avatar: 'https://i.pravatar.cc/64?img=19',
    },
    type: 'Audit',
    requestedOn: '2025-07-16',
    completedOn: '2025-07-20',
    justification: 'I want to help...',
    status: 'Submitted',
    progress: '100%',
  },
  {
    id: 'd-3',
    label: 'Network Security Audit',
    organization: {
      name: 'Teralink NGO',
      sub: '',
      avatar: 'https://i.pravatar.cc/64?img=5',
    },
    type: 'Audit',
    requestedOn: '2025-07-16',
    completedOn: '2025-07-20',
    justification: 'I want to help...',
    status: 'Accepted',
    progress: '100%',
  },
  {
    id: 'd-4',
    label: 'Network Security Audit',
    organization: {
      name: 'Teralink NGO',
      sub: '',
      avatar: 'https://i.pravatar.cc/64?img=8',
    },
    type: 'Audit',
    requestedOn: '2025-07-16',
    completedOn: '2025-07-20',
    justification: 'I want to help...',
    status: 'Accepted',
    progress: '100%',
  },
  {
    id: 'd-5',
    label: 'Network Security Audit',
    organization: {
      name: 'Teralink NGO',
      sub: '',
      avatar: 'https://i.pravatar.cc/64?img=25',
    },
    type: 'Audit',
    requestedOn: '2025-07-16',
    completedOn: null,
    justification: 'I want to help...',
    status: 'Pending',
    progress: '—',
  },
];
